#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/clone ensure=absent force=true
puppet resource file /tmp/clone ensure=directory
cd /tmp/clone
git clone https://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@github.com/chai-ru-yi/22053379_repo.git
cp -p /tmp/clone/22053379_repo/22053379_index.html /var/www/html/index
